---
- hosts: all
  user: ubuntu
  tasks:
  - name: do release upgrade
    shell: do-release-upgrade -f DistUpgradeViewNonInteractive
    become: yes
  - name: rebooting
    shell: reboot
    async: 0
    poll: 0
    become: yes
  - name: waiting for server to come back
    local_action: wait_for host={{ ansible_ssh_host }} state=started
