- hosts: wordpress
  remote_user: user
  become: yes
  become_user: www-data
  tasks:
  - name: update core
    command: wp core update
    register: result
    changed_when: '"up to date" not in result.stdout'
    args:
        chdir: /home/wordpress/public_html

  - name: update plugin
    command: wp plugin update --all
    register: result
    changed_when: '"already updated" not in result.stdout'
    args:
        chdir: /home/wordpress/public_html
